<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('adminhtml')->__('Log into Magento Admin Page') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <link rel="icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('favicon.ico') ?>" type="image/x-icon" />

    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getJsUrl('mage/captcha.js') ?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
</head>
<body id="page-login" onload="document.forms.loginForm.code.focus();">
<div class="login-container">
    <div class="login-box">
        <form method="post" action="" id="loginForm" autocomplete="off">
            <div class="login-form">
                <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                <h2><?php echo Mage::helper('nortoneo_twofactorauth')->__('Two Factor Authentication') ?></h2>
                <div id="messages">
                    <?php echo $this->getMessagesBlock()->toHtml() ?>
                </div>
                <div class="input-box input-left"><label for="code"><?php echo Mage::helper('nortoneo_twofactorauth')->__('Authentication Code:') ?></label><br/>
                    <input type="text" id="code" name="code" value="" class="required-entry input-text" /></div>
                <div class="clear"></div>
                <div class="form-buttons">
                    <?php if(Mage::helper('nortoneo_twofactorauth')->getCurrentUserSettingsModel()->isCodeByEmailEnabled()): ?>
                    <a class="left" href="<?php echo Mage::helper('adminhtml')->getUrl('nortoneo_twofactorauth/login/resend', array('_nosecret' => true)) ?>"><?php echo Mage::helper('nortoneo_twofactorauth')->__('Resend code') ?></a>
                    <?php endif; ?>
                    <input type="submit" class="form-button" value="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('nortoneo_twofactorauth')->__('Enter Code')) ?>" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('nortoneo_twofactorauth')->__('Authentication Code')) ?>" /></div>
            </div>
        </form>
        <div class="bottom"></div>
        <script type="text/javascript">
            var loginForm = new varienForm('loginForm');
        </script>
    </div>
</div>
</body>
</html>

